AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'client/**/*'
    - 'client.old/**/*'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 35
Metrics/ClassLength:
  Max: 500
